### ISSUE TITLE
No Random No Bias - Fix Minor Typo

### ISSUE THREAD

**Issue by rasti37** [cryptohack/issues-tracker#2]
[05/19/2023] Mentioned in Discord by @ htns.

> Meanwhile in [ECC → No random, no bias] there's this line...
    \
    y = pow(ysqr, (p+3)//4, p)

<details> 
  <summary>Potential Fix:</summary>
      > OP : maybe clearer to write it as (p+1)//4 since it's equal to (p+1)/4 anyway? Or is it a misdirection
</details>

**Comment by hyperreality** [comment]
Thanks this will be fixed in the next challenge release
