### ISSUE TITLE
CryptoHack Discord Bot - Exclude archived challenges from the challenge count

### ISSUE THREAD

**Issue by rasti37** [cryptohack/issues-tracker#3]
This has been around for quite some time.

[08/08/2022] - Mentioned in Discord by @ Shadowwws:

> The archive challenges are included in the challenge count in the ⁠bot-chat commands, I don’t know if it’s intended ( I personally prefer if they’re not )

**Comment by hyperreality** [comment]
@RobinJadoul What do you think, should we exclude these? I personally don't mind, but I suppose it is making players feel that their ranking is incomplete even though they have finished all main challenges on the site

**Comment by RobinJadoul** [comment]
As far as I remember, this is a result of how the (wechall) API reports the stats, so this is in the first place something to fix on the server side.
I tend to agree that it looks weird, especially when the total does not include the archive challenges.
You could end up having "solved" the total amount of challenges simply by solving a few in the archive and *not* completing the "main" challenges.

I'd go for splitting the reporting into two parts for the bot/whois, which would however involve migrating to a different or even new API endpoint for the bot.

**Comment by hyperreality** [comment]
@RobinJadoul You're right, it's best to fix this at the root and fix the data being reported to Wechall. I'll make sure to do that before next challenge release

**Comment by hyperreality** [comment]
Fixed in latest release
